### PR TITLE
Fix refs for React 16, update deps

### PR DESCRIPTION
**Pull request by GeKorm**
The real base is 5af7a3b604734c45c98880f1d9069bd4f31dac5f
This is to make the migration to v3 easier for users.

### CODE REVIEW

**Comment by marnusw** [comment]
Thanks @GeKorm, this is a good idea. I've merged this into the appropriate base, but when I run the demo as is it breaks on the carousel demo in particular and the others also don't respond to well to rapid clicks. Would you have time to look at the carousel before I release this?

I'll have time for this on the weekend again, at which point I should manage to fix the open issue with non-updating children. If you can't look into this here I might also fix this over the weekend.

**Comment by GeKorm** [comment]
The carousel breaks because it's mutating the props.
Converting
```javascript
style.cursor = 'pointer'
```
to
```javascript
    const newStyle = {...style, cursor: 'pointer'}

    return (
      <div style={newStyle} onClick={this.handleClick}>
```
fixes it. No clue about the rapid clicks glitch I'm afraid.

**Comment by marnusw** [comment]
Thanks, I've released v2.2.2.

**Comment by evisong** [comment]
> Thanks, I've released v2.2.2.

Hi, @marnusw, thanks for this great lib! 

Actually we have some old project depending on this version, and we're trying to look into src for debugging purpose. However the `v2.2.2` is not in tag list https://github.com/marnusw/react-css-transition-replace/tags , is there any chance to create this git tag? Thanks.

**Comment by evisong** [comment]
> > Thanks, I've released v2.2.2.
> 
> Hi, @marnusw, thanks for this great lib!
> 
> Actually we have some old project depending on this version, and we're trying to look into src for debugging purpose. However the `v2.2.2` is not in tag list https://github.com/marnusw/react-css-transition-replace/tags , is there any chance to create this git tag? Thanks.

I've created a branch for `v2.2.2` based on this PR, in case others need it.

https://github.com/evisong/react-css-transition-replace/tree/dev-2.2.2-local

**Pull request merged**
