### PR TITLE
Prevent container from getting stuck at height: 0

### PR DESCRIPTION
**Pull request by fixpunkt**
This fixes https://github.com/marnusw/react-css-transition-replace/issues/6 for me.

### CODE REVIEW

**Comment by marnusw** [comment]
Thanks for submitting this @fixpunkt, it looks like a simple enough fix. I should finally have time to work on this library again during next week at which time I'll review this properly and merge.

**Comment by marnusw** [comment]
I thought I should mention that I have spent some time on this but I don't have a solution yet. Your change here apparently reduces the chance of the issue occurring, but it doesn't solve it. I'm pretty sure this occurs when the state changes while the height transition is waiting for the timeout to occur. Setting the timeout to a longer value makes it easier to reproduce the issue. I could just make it really short, but that doesn't seem like it's solving the actual problem, and if the state is changed programatically there are no guarantees even with a short timeout.

**Comment by satazor** [comment]
I'm experiencing this problem and I hope it gets fixed soon. Can I help somehow?

**Comment by marnusw** [comment]
I believe this problem has finally been solved. (I sincerely hope it has!) I think this happened due to a race condition when the height transition was started one tick after updating the children in the state. If at that point the `nextChild` had not been rendered to the DOM yet there wouldn't be a new height to transition to, and instead the component was set to zero height. 

This PR did put me on the right track thought, so thanks for this contribution @fixpunkt!

Let me know if this issue crops up again in any of your use cases.

**Pull request closed without merging**
